
// DO NOT EDIT THIS FILE!
// it is auto generated via GamePadInput.tt

using Microsoft.Xna.Framework.Input;

namespace BytingLib
{
    public partial class GamePadInput
    {
		public IKey DPadUp => GetKey(Buttons.DPadUp);
		public IKey DPadDown => GetKey(Buttons.DPadDown);
		public IKey DPadLeft => GetKey(Buttons.DPadLeft);
		public IKey DPadRight => GetKey(Buttons.DPadRight);
		public IKey Start => GetKey(Buttons.Start);
		public IKey Back => GetKey(Buttons.Back);
		public IKey LeftStick => GetKey(Buttons.LeftStick);
		public IKey RightStick => GetKey(Buttons.RightStick);
		public IKey LeftShoulder => GetKey(Buttons.LeftShoulder);
		public IKey RightShoulder => GetKey(Buttons.RightShoulder);
		public IKey BigButton => GetKey(Buttons.BigButton);
		public IKey A => GetKey(Buttons.A);
		public IKey B => GetKey(Buttons.B);
		public IKey X => GetKey(Buttons.X);
		public IKey Y => GetKey(Buttons.Y);
		public IKey LeftThumbstickLeft => GetKey(Buttons.LeftThumbstickLeft);
		public IKey RightTrigger => GetKey(Buttons.RightTrigger);
		public IKey LeftTrigger => GetKey(Buttons.LeftTrigger);
		public IKey RightThumbstickUp => GetKey(Buttons.RightThumbstickUp);
		public IKey RightThumbstickDown => GetKey(Buttons.RightThumbstickDown);
		public IKey RightThumbstickRight => GetKey(Buttons.RightThumbstickRight);
		public IKey RightThumbstickLeft => GetKey(Buttons.RightThumbstickLeft);
		public IKey LeftThumbstickUp => GetKey(Buttons.LeftThumbstickUp);
		public IKey LeftThumbstickDown => GetKey(Buttons.LeftThumbstickDown);
		public IKey LeftThumbstickRight => GetKey(Buttons.LeftThumbstickRight);

    }
}