// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsInputRecordings.tt
	public partial class InputInputRecordings : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc startRecording;
		protected readonly BoolFunc stopRecording;

		public virtual InputBoolState StartRecording => startRecording.GetState(updater);
		public virtual InputBoolState StopRecording => stopRecording.GetState(updater);

		public InputInputRecordings(InputBinds<BindsInputRecordings> b, InputUpdater updater)
		{
			this.updater = updater;
			
			startRecording = new(() => b.Binds.StartRecording);
			stopRecording = new(() => b.Binds.StopRecording);

			InitInput(startRecording);
			InitInput(stopRecording);
		}

		protected void InitInput(Input input)
		{
			updater.AddOutput(input);
			disposables.Use(input);
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

