// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsInputRecordings.tt
	public partial class InputInputRecordings : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc startRecording;
		protected readonly BoolFunc stopRecording;

		public virtual InputBoolState StartRecording => startRecording.GetState(updater);
		public virtual InputBoolState StopRecording => stopRecording.GetState(updater);

		public InputInputRecordings(BindsInputRecordings binds, InputUpdater updater)
		{
			this.updater = updater;
			
			InitInput(out startRecording, new(() => binds.StartRecording));
			InitInput(out stopRecording, new(() => binds.StopRecording));

			
		}
		
		protected void InitInput<T>(out T inputOut, T input) where T : Input
		{
			updater.AddOutput(input);
			disposables.Use(input);
            inputOut = input;
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

