// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsCanvas.tt
	public partial class InputCanvas : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly Vector2Func mousePosition;
		protected readonly BoolFunc click;
		protected readonly IntFunc scroll;

		public virtual InputVector2State MousePosition => mousePosition.GetState(updater);
		public virtual InputBoolState Click => click.GetState(updater);
		public virtual InputIntState Scroll => scroll.GetState(updater);

		public InputCanvas(InputBinds<BindsCanvas> b, InputUpdater updater)
		{
			this.updater = updater;
			
			mousePosition = new(() => b.Binds.MousePosition);
			click = new(() => b.Binds.Click);
			scroll = new(() => b.Binds.Scroll);

			InitInput(mousePosition);
			InitInput(click);
			InitInput(scroll);
		}

		protected void InitInput(Input input)
		{
			updater.AddOutput(input);
			disposables.Use(input);
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

