// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsCanvas.tt
	public partial class InputCanvas : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly Vector2Func mousePosition;
		protected readonly BoolFunc click;
		protected readonly IntFunc scroll;

		public virtual InputVector2State MousePosition => mousePosition.GetState(updater);
		public virtual InputBoolState Click => click.GetState(updater);
		public virtual InputIntState Scroll => scroll.GetState(updater);

		public InputCanvas(BindsCanvas binds, InputUpdater updater)
		{
			this.updater = updater;
			
			InitInput(out mousePosition, new(() => binds.MousePosition));
			InitInput(out click, new(() => binds.Click));
			InitInput(out scroll, new(() => binds.Scroll));

			
		}
		
		protected void InitInput<T>(out T inputOut, T input) where T : Input
		{
			updater.AddOutput(input);
			disposables.Use(input);
            inputOut = input;
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

