// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsMeta.tt
	public partial class InputMeta : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc screenshot;
		protected readonly BoolFunc screenshotAndCopy;
		protected readonly BoolFunc screenshotAndCopyFile;
		protected readonly BoolFunc screenshotDelayed;
		protected readonly BoolFunc toggleFullscreen;
		protected readonly BoolFunc interruptReplay;
		protected readonly BoolFunc swapScreen;

		public virtual InputBoolState Screenshot => screenshot.GetState(updater);
		public virtual InputBoolState ScreenshotAndCopy => screenshotAndCopy.GetState(updater);
		public virtual InputBoolState ScreenshotAndCopyFile => screenshotAndCopyFile.GetState(updater);
		public virtual InputBoolState ScreenshotDelayed => screenshotDelayed.GetState(updater);
		public virtual InputBoolState ToggleFullscreen => toggleFullscreen.GetState(updater);
		public virtual InputBoolState InterruptReplay => interruptReplay.GetState(updater);
		public virtual InputBoolState SwapScreen => swapScreen.GetState(updater);

		public InputMeta(BindsMeta binds, InputUpdater updater)
		{
			this.updater = updater;
			
			InitInput(out screenshot, new(() => binds.Screenshot));
			InitInput(out screenshotAndCopy, new(() => binds.ScreenshotAndCopy));
			InitInput(out screenshotAndCopyFile, new(() => binds.ScreenshotAndCopyFile));
			InitInput(out screenshotDelayed, new(() => binds.ScreenshotDelayed));
			InitInput(out toggleFullscreen, new(() => binds.ToggleFullscreen));
			InitInput(out interruptReplay, new(() => binds.InterruptReplay));
			InitInput(out swapScreen, new(() => binds.SwapScreen));

			
		}
		
		protected void InitInput<T>(out T inputOut, T input) where T : Input
		{
			updater.AddOutput(input);
			disposables.Use(input);
            inputOut = input;
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

