// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsMeta.tt
	public partial class InputMeta : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc screenshot;
		protected readonly BoolFunc screenshotDelayed;
		protected readonly BoolFunc toggleFullscreen;
		protected readonly BoolFunc interruptReplay;
		protected readonly BoolFunc swapScreen;

		public virtual InputBoolState Screenshot => screenshot.GetState(updater);
		public virtual InputBoolState ScreenshotDelayed => screenshotDelayed.GetState(updater);
		public virtual InputBoolState ToggleFullscreen => toggleFullscreen.GetState(updater);
		public virtual InputBoolState InterruptReplay => interruptReplay.GetState(updater);
		public virtual InputBoolState SwapScreen => swapScreen.GetState(updater);

		public InputMeta(InputBinds<BindsMeta> b, InputUpdater updater)
		{
			this.updater = updater;
			
			screenshot = new(() => b.Binds.Screenshot);
			screenshotDelayed = new(() => b.Binds.ScreenshotDelayed);
			toggleFullscreen = new(() => b.Binds.ToggleFullscreen);
			interruptReplay = new(() => b.Binds.InterruptReplay);
			swapScreen = new(() => b.Binds.SwapScreen);

			InitInput(screenshot);
			InitInput(screenshotDelayed);
			InitInput(toggleFullscreen);
			InitInput(interruptReplay);
			InitInput(swapScreen);
		}

		protected void InitInput(Input input)
		{
			updater.AddOutput(input);
			disposables.Use(input);
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

