// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsControlGameSpeed.tt
	public partial class InputControlGameSpeed : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc speedUp10;
		protected readonly BoolFunc speedUp100;
		protected readonly BoolFunc halt;
		protected readonly BoolFunc forwardOneFrame;

		public virtual InputBoolState SpeedUp10 => speedUp10.GetState(updater);
		public virtual InputBoolState SpeedUp100 => speedUp100.GetState(updater);
		public virtual InputBoolState Halt => halt.GetState(updater);
		public virtual InputBoolState ForwardOneFrame => forwardOneFrame.GetState(updater);

		public InputControlGameSpeed(InputBinds<BindsControlGameSpeed> b, InputUpdater updater)
		{
			this.updater = updater;
			
			speedUp10 = new(() => b.Binds.SpeedUp10);
			speedUp100 = new(() => b.Binds.SpeedUp100);
			halt = new(() => b.Binds.Halt);
			forwardOneFrame = new(() => b.Binds.ForwardOneFrame);

			InitInput(speedUp10);
			InitInput(speedUp100);
			InitInput(halt);
			InitInput(forwardOneFrame);
		}

		protected void InitInput(Input input)
		{
			updater.AddOutput(input);
			disposables.Use(input);
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

