// THIS FILE IS GENERATED
namespace BytingLib
{
	// THIS CLASS IS GENERATED by BindsControlGameSpeed.tt
	public partial class InputControlGameSpeed : IDisposable
	{
		protected readonly InputUpdater updater;
		protected readonly DisposableContainer disposables = new();

		protected readonly BoolFunc speedUp10;
		protected readonly BoolFunc speedUp100;
		protected readonly BoolFunc halt;
		protected readonly BoolFunc forwardOneFrame;

		public virtual InputBoolState SpeedUp10 => speedUp10.GetState(updater);
		public virtual InputBoolState SpeedUp100 => speedUp100.GetState(updater);
		public virtual InputBoolState Halt => halt.GetState(updater);
		public virtual InputBoolState ForwardOneFrame => forwardOneFrame.GetState(updater);

		public InputControlGameSpeed(BindsControlGameSpeed binds, InputUpdater updater)
		{
			this.updater = updater;
			
			InitInput(out speedUp10, new(() => binds.SpeedUp10));
			InitInput(out speedUp100, new(() => binds.SpeedUp100));
			InitInput(out halt, new(() => binds.Halt));
			InitInput(out forwardOneFrame, new(() => binds.ForwardOneFrame));

			
		}
		
		protected void InitInput<T>(out T inputOut, T input) where T : Input
		{
			updater.AddOutput(input);
			disposables.Use(input);
            inputOut = input;
		}

		public void Dispose()
		{
			disposables.Dispose();
		}
	}
}

